name = "packtester"
main = ".opennext/dist/index.mjs"
compatibility_date = "2024-01-01"

# Cloudflare Workers configuration for Next.js using OpenNext
[build]
command = "npm exec opennextjs-cloudflare"
cwd = "."

[[kv_namespaces]]
binding = "BINDING_NAME"
id = "8c1e4ee50d514f33994dbab23c506d25"